import { Providers } from '@/shared/components/providers'
import cn from '@/shared/helpers/cn'
import { DefaultLayout } from '@/shared/layouts'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Sora } from 'next/font/google'

const sora = Sora({
    variable: '--font-sora',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={cn(sora.variable, 'antialiased')}>
                <Providers>
                    <DefaultLayout>{children}</DefaultLayout>
                </Providers>
            </body>
        </html>
    )
}
